### ISSUE TITLE
Couple of questions about raft implementation

### ISSUE THREAD

**Issue by FZambia** [otoolep/hraftd#1]
Hello! Thanks for your work on this implementation, I wanted to understand raft for a long time and your work helped to start. I have two questions:

1) 3 node situation. When we terminate leader another node becomes a leader. And new leader tries to connect to terminated node periodically. What if we terminated that node intentionally (forever) and don't want new leader attempting to connect to it? Maybe I am missing some core idea here.

2) Another question is about posting to `/key` endpoint. You wrote in README that leader-forwarding is not implemented. How external application can understand what's the current leader address to post new  keys?

**Comment by otoolep** [comment]
Q1: in that case the node must be deliberately removed from the cluster. That support is not in this hraftd, though it would be easy enough to add.

Q2: Again, hraftd is simple so you would just need to hit each node until one accepts the set request. It would be easy enough for the non-leader node to include in the response which node is leader so the client would know where to go.

**Comment by FZambia** [comment]
Thanks a lot!
