### ISSUE TITLE
Run hraftd on multi machines.

### ISSUE THREAD

**Issue by scorpiovn** [otoolep/hraftd#10]
How to run a hdraft cluster on multi machines?

**Comment by scorpiovn** [comment]
resolved

**Comment by otoolep** [comment]
Glad you sorted it out @scorpiovn -- I have added a detailed example of a clustering here: https://github.com/otoolep/hraftd/blob/master/CLUSTERING.md

**Comment by scorpiovn** [comment]
@otoolep Thank you very much.
