### ISSUE TITLE
Failed to decode incoming command: unknown rpc type 80

### ISSUE THREAD

**Issue by s4ayub** [otoolep/hraftd#12]
Upon trying to set a key with the following command:
` curl -XPOST localhost:12000/key -d '{"user1": "batman"}'`
I get the following error:
```
2017/09/02 16:35:40 [DEBUG] raft-net: :12000 accepted connection from: [::1]:54508
2017/09/02 16:35:40 [ERR] raft-net: Failed to decode incoming command: unknown rpc type 80
```
The Join requests work though. Is this an issue with hashicorp/raft or because I updated to go 1.9?

**Comment by otoolep** [comment]
You're sending the requests to the wrong port, assuming your started it using the defaults. Please read the [documentation](https://github.com/otoolep/hraftd/blob/master/README.md#reading-and-writing-keys) carefully.
```
$ hraftd -h
Usage: ./hraftd [options] <raft-data-path> 
  -haddr string
        Set the HTTP bind address (default ":11000")
  -join string
        Set join address, if any
  -raddr string
        Set Raft bind address (default ":12000")
```
Instead run `curl -XPOST localhost:11000/key -d '{"user1": "batman"}'`

**Comment by s4ayub** [comment]
@otoolep  You're right! thank you!
