### ISSUE TITLE
When node dies, the next promoted master keeps trying to connect to the dead ones

### ISSUE THREAD

**Issue by codeadict** [otoolep/hraftd#16]
Not sure if this is the expected functionality, but when i kill a master, the next node promoted to master keeps trying to reach the old one, generating bunch of logs like:

```
2017/10/24 13:48:42 [DEBUG] raft: Votes needed: 2
2017/10/24 13:48:42 [DEBUG] raft: Vote granted from node2 in term 68. Tally: 1
2017/10/24 13:48:44 [WARN] raft: Election timeout reached, restarting election
2017/10/24 13:48:44 [INFO] raft: Node at :12002 [Candidate] entering Candidate state in term 69
2017/10/24 13:48:44 [ERR] raft: Failed to make RequestVote RPC to {Voter node0 :12000}: dial tcp :12000: getsockopt: connection refused
2017/10/24 13:48:44 [ERR] raft: Failed to make RequestVote RPC to {Voter node1 :12001}: dial tcp :12001: getsockopt: connection refused
```

**Comment by otoolep** [comment]
Yes, this is expected. hraftd is not a production-grade system and removing nodes is not supported.

**Comment by otoolep** [comment]
Just to be clear, the system can tolerate node failures, but there is no support for telling the cluster to forget about that node forever. A production-grade system like [rqlite](https://github.com/rqlite/rqlite) does support node removal -- see https://github.com/rqlite/rqlite/blob/master/DOC/CLUSTER_MGMT.md
