### ISSUE TITLE
stale reads.

### ISSUE THREAD

**Issue by komuW** [otoolep/hraftd#22]
The readme says `Because any node will answer a GET request, and nodes may "fall behind" updates, stale reads are possible.` 
If I wanted to fix that, how would I go about it? 
First I thought that if I took[1] and replaced it with 
```go
func (s *Store) Get(key string) (string, error) {
      if s.raft.State() != raft.Leader {
		return fmt.Errorf("not leader")
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	return s.m[key], nil
}
```
then I would have cured the ail. 
But then, I came across[2], and from that thread `The leader should check before serving any read if it is actually still the leader. It can happen, that a leader has not detected a network partition since heatbeat failures are not detected instantaneously.`
so it seems like my code above wouldn't be enough to solve it.
So how would I completely solve it??

ref:
1. https://github.com/otoolep/hraftd/blob/915a171dbebdc07ed4dac22e2b06a87a4709b638/store/store.go#L109-L113
2. https://github.com/rqlite/rqlite/issues/5

**Comment by otoolep** [comment]
@komuW -- you need to send the query through the log to solve this final case (known as "strong" consistency in rqlite).

I suggest you study the rqlite source code, and learn what happens when a query request specifies "strong" consistency.

https://github.com/rqlite/rqlite/blob/master/store/store.go#L527

**Comment by otoolep** [comment]
This should be enough to learn how rqlite does it, but feel free to let me know if it doesn't.

**Comment by otoolep** [comment]
Just in case it is not clear, you need to port what rqlite does to hraftd.

**Comment by komuW** [comment]
just so that it's super clear, when you say; `you need to send the query through the log`    
do you mean;
```go
f := s.raft.Apply(b, raftTimeout)
return f.Error()
```
where b is the json-marshaled command?

**Comment by otoolep** [comment]
Yeah, that is what I mean, and what rqlite does.

**Comment by komuW** [comment]
Thanks for your help. I'll dig into sqlite this week
