### ISSUE TITLE
a question about apply  log in candidate node

### ISSUE THREAD

**Issue by GitRainy** [otoolep/hraftd#25]
i try to apply log in a candidate node, i know it must redirect to leader then execute,but i don't hope achieve this through http. In fact, i only hope i can  achieve this through communication between its own clusters, but i don't how to do it,can you give me some ideas? thanks

**Comment by otoolep** [comment]
I don't fully understand your question. However I suggest you send your question to this mailing list:

https://groups.google.com/forum/#!forum/raft-dev
