### ISSUE TITLE
how to make sure log has been commited ?

### ISSUE THREAD

**Issue by timchenxiaoyu** [otoolep/hraftd#32]
case "POST":
		// Read the value from the POST body.
		m := map[string]string{}
		if err := json.NewDecoder(r.Body).Decode(&m); err != nil {
			w.WriteHeader(http.StatusBadRequest)
			return
		}
		for k, v := range m {
			if err := s.store.Set(k, v); err != nil {
				w.WriteHeader(http.StatusInternalServerError)
				return
			}
		}

api return success,but logs may be not commited ?

**Comment by otoolep** [comment]
How, exactly? `s.store.Set` commits to the log. If it fails, an error is returned.

**Comment by otoolep** [comment]
Please re-open if you think I am mistaken, and include more line-by-line details of what you think is wrong.

**Comment by timchenxiaoyu** [comment]
https://github.com/hashicorp/raft/issues/397#issuecomment-610125141

**Comment by otoolep** [comment]
Simply look at the implementation of the function. It does the right thing.

**Comment by otoolep** [comment]
`store.Set()` that is.

**Comment by timchenxiaoyu** [comment]
thanks！
