### ISSUE TITLE
hraftd wont start

### ISSUE THREAD

**Issue by noelzubin** [otoolep/hraftd#33]
`$GOPATH/bin/hraftd -id node0 ~/node0` throws error
 `failed to open store: local bind address is not advertisable`

**Comment by noelzubin** [comment]
this wouldnt work when i run it after using `go get`.
but if i clone the repo and run `go run main.go` it works correctly.

**Comment by otoolep** [comment]
Thanks or your report, I can reproduce this. Something has changed, presumably in the dependencies, because this used to work fine.

I'll see if I can track it down. In the meantime you can work around it by explicitly specifying the network addresses e.g.
```
$GOPATH/bin/hraftd -haddr 127.0.0.1:11000 -raddr 127.0.0.1:12000 -id node0 ~/node0
```

**Comment by otoolep** [comment]
I've updated the README so this should work now.

**Comment by paulm17** [comment]
Sadly, I'm getting the same issue as well.

**Comment by otoolep** [comment]
@paulm17 -- please provide more information. What OS are you running, what command you issued, and what you got back. Show me the session.

**Comment by paulm17** [comment]
@otoolep Thanks for the reply, appreciate it.

I'm running on a mac.

I've recorded the session: https://streamable.com/dp1ko4

I've also tried creating a binary and running that.  Same issue.

**Comment by otoolep** [comment]
@paulm17 -- just so I am clear, you are expecting `hraftd` to listen on all interfaces? It doesn't actually support that, but the error code could be clearer about that.

**Comment by paulm17** [comment]
@otoolep aha, now that you mentioned that.

```
go run main.go -haddr 127.0.0.1:11000 -raddr 127.0.0.1:12000 -id node0 ~/node0
go run main.go -id node1 -haddr 127.0.0.1:11001 -raddr 127.0.0.1:12001 -join 127.0.0.1:11000 ~/node1
go run main.go -id node2 -haddr 127.0.0.1:11002 -raddr 127.0.0.1:12002 -join 127.0.0.1:11000 ~/node2
```

Works for me now.  Many thanks!

**Comment by otoolep** [comment]
However, I see the README told you to do this. I'll fix that.

**Comment by otoolep** [comment]
https://github.com/otoolep/hraftd/commit/8cbbffbf03b39589d7faac197d695e1090f9ec66
