### ISSUE TITLE
Additions

### ISSUE THREAD

**Issue by euforia** [otoolep/hraftd#4]
First off thank you so much for posting this.  I has been very helpful.

I've added a couple of features if you are interested. Particularly:

- Optimization of the command struct for logs.
- Forwarding requests to the leader ( added an RPC server to the store) including join requests.
- A KVStore interface to support other types of stores.

My ultimate goal is provide a generic framework to allow others to use the framework to embed a key value store into their applications.

You can find the repo here: https://github.com/euforia/hraftd/tree/forwarding.  This is still a work in progress.

Let me know what you think.

**Comment by otoolep** [comment]
Very nice, thanks for letting me know @euforia 

I've been thinking about adding leader-forwarding to my own hraftd project https://github.com/rqlite/rqlite, but decided against it for now. Instead I added leader-redirection (well, it's what I call it). With rqlite, a non-leader node returns HTTP 301 with the leader hostname, telling the client to go elsewhere. But i may yet add it to rqlite.

One general guideline I have found valuable, and might interest you, is to keep you use of third party libraries rare. Obviously you need to bring in Hashicorp Raft, but think carefully about using other package outside the standard library. We found this guideline very effective at keeping our code consistent at InfluxDB.

https://blog.gopheracademy.com/advent-2014/case-against-3pl/

**Comment by otoolep** [comment]
I will check back on your code sometime, let me know when it's complete.

**Comment by euforia** [comment]
I do like the idea of a redirect as well.  Thanx for the blog post regarding 3rd party libs.  It has some very interesting points.

rqlite seems to be aiming for the same concepts i am looking at.  I'm trying to do the same for boltdb or any storage backend for that matter. 

Maybe we can collaborate and make a generic swappable `storage` interface.  Let me know what you think.

Thanx once again for the response.

**Comment by otoolep** [comment]
A generic `storage` interface is definitely an interesting idea, it'd be a challenge to come up with an interface that would work for both simple k-v stores and relational. I'd be curious to see if you can do it. :-)
