### ISSUE TITLE
Extended example of how to share cleaned up state when a new peer joins?

### ISSUE THREAD

**Issue by leehambley** [otoolep/hraftd#9]
Please forgive my using GitHub issues for asking a question. I've been looking for an example of how Raft should deal with a peer joining after log compaction to get the "current state".

Example:

1. Happily running a cluster of any size.
2. Lots of logs (say, 10M) taken on, consensus always tight, eventually the log can be compacted.
3. New peer joins.

Should the new peer catch-up on 10M events, or should it be given some snapshot of state to get caught-up, and if so, how is it typically done?

---

Actually, my use-case, and the reason I'm looking into raft is as a backend for an event source database, where the "my database is a stream of events" translates very very well to raft's distributed linear log concept. I'm not sure however if one should snapshot and store binary logs, and have new peers get a binary snapshot state rather than keeping all the messages in the history. I'm asking myself if my use-case even *needs* log compaction when the log is my database.

**Comment by otoolep** [comment]
@leehambley -- thanks for your question.

You don't need to do anything. If a new node joins the cluster that node is sent a snapshot from the master, and the node first installs that. It's all handled by Raft.

The code that a node uses to restore from a received snapshot is here: https://github.com/otoolep/hraftd/blob/master/store/store.go#L202

I'm closing this, but feel free to ask more questions.

**Comment by leehambley** [comment]
Thanks for a solid explanation, I totally missed that when reading the literature. Very, very much appreciated!
